# Generated by Django 3.2.4 on 2021-07-13 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_user_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quize',
            name='category',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='quize',
            name='file',
            field=models.FileField(null=True, upload_to='file'),
        ),
        migrations.AlterField(
            model_name='quize',
            name='text',
            field=models.TextField(max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='quize',
            name='title',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
